# Generated by Django 4.0.5 on 2022-07-15 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0003_alter_category_cat_img_alter_category_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
