# Generated by Django 4.0.5 on 2022-06-29 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysqlcrud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(default='', max_length=20),
        ),
    ]
