# Generated by Django 4.0.5 on 2022-06-29 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysqlcrud', '0004_alter_student_language_alter_student_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='country',
            field=models.CharField(default='', max_length=20),
        ),
    ]
