# Generated by Django 4.0.5 on 2022-07-04 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userRegisterLoginApp', '0003_alter_signup_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='phone',
        ),
    ]
