# Generated by Django 4.0.5 on 2022-07-04 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userRegisterLoginApp', '0004_remove_signup_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='email',
            field=models.CharField(default='', max_length=50),
        ),
    ]
