# Generated by Django 4.0.5 on 2022-07-12 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoAjax', '0002_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='country',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
